# Generated by Django 3.2.6 on 2022-04-03 00:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F', models.CharField(default='q', max_length=1)),
                ('FS', models.CharField(default='w', max_length=1)),
                ('G', models.CharField(default='e', max_length=1)),
                ('GS', models.CharField(default='r', max_length=1)),
                ('A', models.CharField(default='t', max_length=1)),
                ('AS', models.CharField(default='y', max_length=1)),
                ('B', models.CharField(default='u', max_length=1)),
                ('C2', models.CharField(default='i', max_length=1)),
                ('CS2', models.CharField(default='o', max_length=1)),
                ('D2', models.CharField(default='p', max_length=1)),
                ('DS2', models.CharField(default='a', max_length=1)),
                ('E2', models.CharField(default='s', max_length=1)),
                ('F2', models.CharField(default='d', max_length=1)),
                ('FS2', models.CharField(default='f', max_length=1)),
                ('G2', models.CharField(default='g', max_length=1)),
                ('GS2', models.CharField(default='h', max_length=1)),
                ('A2', models.CharField(default='j', max_length=1)),
                ('AS2', models.CharField(default='k', max_length=1)),
                ('B2', models.CharField(default='l', max_length=1)),
                ('C3', models.CharField(default='z', max_length=1)),
                ('CS3', models.CharField(default='x', max_length=1)),
                ('D3', models.CharField(default='c', max_length=1)),
                ('DS3', models.CharField(default='v', max_length=1)),
                ('E3', models.CharField(default='b', max_length=1)),
                ('F3', models.CharField(default='n', max_length=1)),
                ('FS3', models.CharField(default='m', max_length=1)),
                ('G3', models.CharField(default='1', max_length=1)),
                ('GS3', models.CharField(default='2', max_length=1)),
                ('A3', models.CharField(default='3', max_length=1)),
                ('AS3', models.CharField(default='4', max_length=1)),
                ('B3', models.CharField(default='5', max_length=1)),
                ('C4', models.CharField(default='6', max_length=1)),
                ('CS4', models.CharField(default='7', max_length=1)),
                ('D4', models.CharField(default='8', max_length=1)),
                ('DS4', models.CharField(default='9', max_length=1)),
                ('E4', models.CharField(default='0', max_length=1)),
                ('F4', models.CharField(default='-', max_length=1)),
                ('FS4', models.CharField(default='=', max_length=1)),
                ('G4', models.CharField(default='[', max_length=1)),
                ('GS4', models.CharField(default=']', max_length=1)),
                ('A4', models.CharField(default=',', max_length=1)),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
