# Generated by Django 3.2.6 on 2022-04-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accordion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyboard',
            old_name='D4',
            new_name='BassA',
        ),
        migrations.RenameField(
            model_name='keyboard',
            old_name='DS4',
            new_name='BassAdom7',
        ),
        migrations.RenameField(
            model_name='keyboard',
            old_name='CS4',
            new_name='BassD',
        ),
        migrations.RenameField(
            model_name='keyboard',
            old_name='C4',
            new_name='BassDmaj',
        ),
        migrations.RenameField(
            model_name='keyboard',
            old_name='E4',
            new_name='BassE',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='A4',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='F4',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='FS4',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='G4',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='GS4',
        ),
    ]
